"use client";

import { useEffect, useState } from "react";
import type { TemplateProps } from "./template-shared";
import { mergeFaq, splitHeadline } from "./template-shared";
import { CtaAction } from "./CtaAction";
import { BrandMark } from "./BrandMark";
import { WaitlistForm } from "@/components/published/WaitlistForm";
import styles from "./minimal-v3.module.css";
import base from "./template-base.module.css";

const FONTS =
  "https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,300;12..96,400;12..96,500;12..96,600;12..96,700&family=Hanken+Grotesk:wght@300;400;500;600&family=JetBrains+Mono:wght@400;500&display=swap";

const LABELS = ["a.", "b.", "c.", "d.", "e.", "f."];

export function MinimalV3Template({
  copy,
  projectName,
  colorMode = "light",
  cssVarStyle,
  isPublished,
  ctaConfig,
  publicationSlug,
  scrollTarget = "#try",
  branding,
}: TemplateProps) {
  const [mode, setMode] = useState(colorMode);
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  const hero = copy.hero;
  const problem = copy.problem;
  const features = copy.features ?? [];
  const proof = copy.proof;
  const cta = copy.cta;
  const faq = mergeFaq(copy);
  const headline = splitHeadline(hero?.headline ?? projectName);
  const proofElements = proof?.elements ?? [];

  useEffect(() => {
    setMode(colorMode);
  }, [colorMode]);

  useEffect(() => {
    const id = "fivvle-minimal-v3-fonts";
    if (!document.getElementById(id)) {
      const link = document.createElement("link");
      link.id = id;
      link.rel = "stylesheet";
      link.href = FONTS;
      document.head.appendChild(link);
    }
  }, []);

  const brandName = projectName.trim() || "Fivvle";

  return (
    <div
      className={`${styles.root} ${base.root}`}
      data-theme={mode}
      style={cssVarStyle}
    >
      <header className={styles.header}>
        <div className={styles.outer}>
          <div className={styles.headerRow}>
            <span className={styles.rail} style={{ paddingTop: 0 }}>
              §
            </span>
            <BrandMark
              branding={branding}
              projectName={projectName}
              variant="minimal-v3"
              showSplitName={false}
              className={styles.brand}
              href="#top"
            />
            <div className={styles.hdrTools}>
              {!isPublished && (
                <button
                  type="button"
                  className={styles.themeBtn}
                  aria-label="Toggle theme"
                  onClick={() => setMode((m) => (m === "dark" ? "light" : "dark"))}
                >
                  {mode === "dark" ? "☀" : "☾"}
                </button>
              )}
              <CtaAction
                config={ctaConfig}
                scrollTarget={scrollTarget}
                className={styles.navCta}
                as="link"
              >
                {hero?.cta ?? "Try it"}
              </CtaAction>
            </div>
          </div>
        </div>
      </header>

      <main id="top">
        {hero && (
          <section className={styles.section}>
            <div className={styles.outer}>
              <div className={styles.grid}>
                <aside className={styles.rail}>
                  <span className={styles.n}>01</span>
                  <br />
                  Hero
                </aside>
                <div className={styles.body}>
                  <div className={styles.eyebrow}>
                    <span className={styles.eyebrowSym}>§</span> Private beta
                  </div>
                  <h1 className={styles.heroTitle}>
                    {headline.main}
                    {headline.accent && (
                      <>
                        <br />
                        <span className={styles.heroAccent}>{headline.accent}</span>
                      </>
                    )}
                  </h1>
                  <p className={styles.heroSub}>{hero.subheadline}</p>
                  <div className={styles.ctaArea}>
                    <CtaAction
                      config={ctaConfig}
                      scrollTarget={scrollTarget}
                      className={styles.cta}
                    >
                      <span>{hero.cta}</span>
                      <span className={styles.ctaArr}>→</span>
                    </CtaAction>
                  </div>
                </div>
                <aside className={styles.margin}>
                  <p className={styles.marginNote}>
                    <span className={styles.k}>Note —</span> Generated by Fivvle
                    from your validation report.
                  </p>
                </aside>
              </div>
            </div>
          </section>
        )}

        {problem && (
          <section className={styles.section} id="premise">
            <div className={styles.outer}>
              <div className={styles.grid}>
                <aside className={styles.rail}>
                  <span className={styles.n}>02</span>
                  <br />
                  Premise
                </aside>
                <div className={styles.body}>
                  <div className={styles.eyebrow}>
                    <span className={styles.eyebrowSym}>§</span> The premise
                  </div>
                  <div className={styles.prose}>
                    <p>
                      <span className={styles.hl}>{problem.heading}</span>{" "}
                      {problem.body}
                    </p>
                  </div>
                </div>
                <aside className={styles.margin} />
              </div>
            </div>
          </section>
        )}

        {features.length > 0 && (
          <section className={styles.section} id="inside">
            <div className={styles.outer}>
              <div className={styles.grid}>
                <aside className={styles.rail}>
                  <span className={styles.n}>03</span>
                  <br />
                  Inside
                </aside>
                <div className={styles.body}>
                  <div className={styles.eyebrow}>
                    <span className={styles.eyebrowSym}>§</span> What&apos;s inside
                  </div>
                  <ol className={styles.featList}>
                    {features.map((f, i) => (
                      <li key={i}>
                        <div className={styles.featRow}>
                          <span className={styles.featNum}>
                            {LABELS[i] ?? `${i + 1}.`}
                          </span>
                          <h3 className={styles.featTtl}>{f.title}</h3>
                          <span className={styles.featNum}>+</span>
                        </div>
                        <p className={styles.featDesc}>{f.description}</p>
                      </li>
                    ))}
                  </ol>
                </div>
                <aside className={styles.margin} />
              </div>
            </div>
          </section>
        )}

        {proofElements.length > 0 && (
          <section className={styles.section} id="voices">
            <div className={styles.outer}>
              <div className={styles.grid}>
                <aside className={styles.rail}>
                  <span className={styles.n}>04</span>
                  <br />
                  Voices
                </aside>
                <div className={styles.body}>
                  <div className={styles.eyebrow}>
                    <span className={styles.eyebrowSym}>§</span> Voices
                  </div>
                  {proofElements.slice(0, 2).map((el, i) => (
                    <div
                      key={i}
                      className={styles.quote}
                      style={i === 1 ? { paddingLeft: "clamp(0px, 4vw, 48px)" } : undefined}
                    >
                      <blockquote>
                        <span className={styles.quoteLead}>—</span> {el}
                      </blockquote>
                      {i === 0 && proof?.headline && (
                        <div className={styles.cite}>{proof.headline}</div>
                      )}
                    </div>
                  ))}
                </div>
                <aside className={styles.margin} />
              </div>
            </div>
          </section>
        )}

        {faq.length > 0 && (
          <section className={styles.section} id="faq">
            <div className={styles.outer}>
              <div className={styles.grid}>
                <aside className={styles.rail}>
                  <span className={styles.n}>05</span>
                  <br />
                  FAQ
                </aside>
                <div className={styles.body}>
                  <div className={styles.eyebrow}>
                    <span className={styles.eyebrowSym}>§</span> Questions
                  </div>
                  {faq.map((item, i) => (
                    <div key={i} className={styles.faqItem}>
                      <button
                        type="button"
                        className={`${styles.faqQ} ${openFaq === i ? styles.faqQOpen : ""}`}
                        aria-expanded={openFaq === i}
                        onClick={() => setOpenFaq(openFaq === i ? null : i)}
                      >
                        <span>{item.question}</span>
                        <span>{openFaq === i ? "−" : "+"}</span>
                      </button>
                      {openFaq === i && (
                        <p className={styles.faqA}>{item.answer}</p>
                      )}
                    </div>
                  ))}
                </div>
                <aside className={styles.margin} />
              </div>
            </div>
          </section>
        )}

        {cta && (
          <section className={styles.ctaSection} id="try">
            <div className={styles.outer}>
              <div className={styles.grid}>
                <aside className={styles.rail}>
                  <span className={styles.n}>06</span>
                  <br />
                  Try it
                </aside>
                <div className={styles.body}>
                  <h2 className={styles.ctaTitle}>
                    {cta.heading.split(".")[0] ?? cta.heading}
                    <br />
                    <em>{cta.subheading || "Decide for yourself."}</em>
                  </h2>
                  <p className={styles.ctaSub}>{cta.subheading}</p>
                  {isPublished &&
                  ctaConfig?.mode === "waitlist" &&
                  publicationSlug ? (
                    <WaitlistForm
                      slug={publicationSlug}
                      buttonLabel={cta.button}
                      className={styles.signup}
                      inputClassName={undefined}
                      buttonClassName={undefined}
                      metaClassName={styles.formMeta}
                    />
                  ) : (
                    <form
                      className={styles.signup}
                      onSubmit={(e) => e.preventDefault()}
                    >
                      <input type="email" placeholder="you@company.com" readOnly />
                      <button type="submit">{cta.button}</button>
                      <p className={styles.formMeta}>
                        No spam · Unsubscribe anytime
                      </p>
                    </form>
                  )}
                </div>
                <aside className={styles.margin} />
              </div>
            </div>
          </section>
        )}
      </main>

      <footer className={styles.footer}>
        <div className={styles.outer}>
          <div className={styles.footerRow}>
            <span className={styles.rail} style={{ paddingTop: 0 }}>
              § End.
            </span>
            <div className={styles.footerMeta}>
              <span className={styles.k}>© {new Date().getFullYear()} {brandName}.</span>{" "}
              Set in Bricolage Grotesque &amp; Hanken Grotesk.
            </div>
            <span className={styles.footerMade}>
              <span className={styles.ast}>*</span> Made with Fivvle
            </span>
          </div>
        </div>
      </footer>
    </div>
  );
}
