"""initial schema: 9 tables for fivvle mvp

Revision ID: 648fe71ca40e
Revises: 
Create Date: 2026-05-11 14:22:05.299018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '648fe71ca40e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('credits_remaining', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('raw_idea', sa.Text(), nullable=False),
    sa.Column('refined_idea', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REFINING', 'REFINED', 'RESEARCHING', 'RESEARCH_PLANNING', 'RESEARCH_SEARCHING', 'RESEARCH_READING', 'RESEARCH_REFLECTING', 'RESEARCH_SYNTHESIZING', 'RESEARCH_READY', 'RESEARCH_FAILED', 'LANDING_GENERATING', 'LANDING_DRAFT', 'LANDING_LIVE', 'ANALYZING', 'COMPLETED', 'ARCHIVED', name='experiment_status', native_enum=False, length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_slug'), 'experiments', ['slug'], unique=True)
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_index(op.f('ix_experiments_user_id'), 'experiments', ['user_id'], unique=False)
    op.create_table('external_api_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_api_calls_experiment_id'), 'external_api_calls', ['experiment_id'], unique=False)
    op.create_table('insight_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('traffic_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conversion_by_source', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('research_takeaways', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('recommendation_type', sa.Enum('PROCEED', 'ITERATE', 'PIVOT', 'KILL', name='insight_recommendation', native_enum=False, length=20), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insight_reports_experiment_id'), 'insight_reports', ['experiment_id'], unique=True)
    op.create_table('landing_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('palette_id', sa.String(length=50), nullable=False),
    sa.Column('font_pair_id', sa.String(length=50), nullable=False),
    sa.Column('density', sa.Enum('COMPACT', 'ROOMY', name='landing_density', native_enum=False, length=20), nullable=False),
    sa.Column('enabled_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('subheadline', sa.String(length=500), nullable=True),
    sa.Column('problem_desc', sa.Text(), nullable=False),
    sa.Column('solution_desc', sa.Text(), nullable=False),
    sa.Column('cta_text', sa.String(length=100), nullable=False),
    sa.Column('cta_type', sa.Enum('WAITLIST', 'INTEREST', 'CONTACT', name='landing_cta_type', native_enum=False, length=20), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('how_it_works', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('faq', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('founder_bio', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('live_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_revalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landing_pages_experiment_id'), 'landing_pages', ['experiment_id'], unique=True)
    op.create_index(op.f('ix_landing_pages_slug'), 'landing_pages', ['slug'], unique=True)
    op.create_table('llm_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=True),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_experiment_id'), 'llm_calls', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_phase'), 'llm_calls', ['phase'], unique=False)
    op.create_table('page_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('source_tag', sa.String(length=100), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_on_page_sec', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('referrer', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_views_experiment_id'), 'page_views', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_page_views_source_tag'), 'page_views', ['source_tag'], unique=False)
    op.create_table('validation_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('research_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('findings_per_question', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('competitors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reddit_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_trends', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('news_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clarity_score', sa.Integer(), nullable=True),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_summary', sa.Text(), nullable=True),
    sa.Column('reflection_loops_used', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_reports_experiment_id'), 'validation_reports', ['experiment_id'], unique=True)
    op.create_table('waitlist_signups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('source_tag', sa.String(length=100), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_signups_experiment_id'), 'waitlist_signups', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_waitlist_signups_source_tag'), 'waitlist_signups', ['source_tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitlist_signups_source_tag'), table_name='waitlist_signups')
    op.drop_index(op.f('ix_waitlist_signups_experiment_id'), table_name='waitlist_signups')
    op.drop_table('waitlist_signups')
    op.drop_index(op.f('ix_validation_reports_experiment_id'), table_name='validation_reports')
    op.drop_table('validation_reports')
    op.drop_index(op.f('ix_page_views_source_tag'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_experiment_id'), table_name='page_views')
    op.drop_table('page_views')
    op.drop_index(op.f('ix_llm_calls_phase'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_experiment_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_landing_pages_slug'), table_name='landing_pages')
    op.drop_index(op.f('ix_landing_pages_experiment_id'), table_name='landing_pages')
    op.drop_table('landing_pages')
    op.drop_index(op.f('ix_insight_reports_experiment_id'), table_name='insight_reports')
    op.drop_table('insight_reports')
    op.drop_index(op.f('ix_external_api_calls_experiment_id'), table_name='external_api_calls')
    op.drop_table('external_api_calls')
    op.drop_index(op.f('ix_experiments_user_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_slug'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
