"""add_copy_json_page_json_to_landing_pages

Revision ID: 0d993ecaf65f
Revises: a7b3e9c2f4d8
Create Date: 2026-06-07 05:39:48.731505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d993ecaf65f'
down_revision: Union[str, Sequence[str], None] = 'a7b3e9c2f4d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landing_pages', sa.Column('copy_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('landing_pages', sa.Column('page_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landing_pages', 'page_json')
    op.drop_column('landing_pages', 'copy_json')
    # ### end Alembic commands ###
