import type { CopyJson, PageJson } from "./types";
import type { TemplateId } from "./templates";
import {
  paletteToCssVars,
  resolveColorPalette,
  type ColorMode,
} from "./color-palettes";

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function cssBlock(vars: Record<string, string>): string {
  return Object.entries(vars)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join("\n");
}

function sectionHtml(copy: CopyJson): string {
  const parts: string[] = [];

  if (copy.hero) {
    parts.push(`
<section class="hero">
  <h1>${esc(copy.hero.headline)}</h1>
  <p class="sub">${esc(copy.hero.subheadline)}</p>
  <a class="btn" href="#cta">${esc(copy.hero.cta)}</a>
</section>`);
  }

  if (copy.problem) {
    parts.push(`
<section class="block">
  <h2>${esc(copy.problem.heading)}</h2>
  <p>${esc(copy.problem.body)}</p>
</section>`);
  }

  if (copy.features?.length) {
    const items = copy.features
      .map(
        (f) =>
          `<li><strong>${esc(f.title)}</strong><p>${esc(f.description)}</p></li>`,
      )
      .join("\n");
    parts.push(`
<section class="block"><h2>Features</h2><ul class="features">${items}</ul></section>`);
  }

  if (copy.proof?.elements?.length) {
    const items = copy.proof.elements.map((e) => `<li>${esc(e)}</li>`).join("");
    parts.push(`
<section class="block"><h2>${esc(copy.proof.headline)}</h2><ul>${items}</ul></section>`);
  }

  const faq = [...(copy.faq ?? [])];
  const objections = copy.objections as
    | { items?: { question: string; answer: string }[] }
    | undefined;
  for (const item of objections?.items ?? []) {
    faq.push(item);
  }
  if (faq.length) {
    const items = faq
      .map(
        (f) =>
          `<details><summary>${esc(f.question)}</summary><p>${esc(f.answer)}</p></details>`,
      )
      .join("\n");
    parts.push(`<section class="block"><h2>FAQ</h2>${items}</section>`);
  }

  if (copy.cta) {
    parts.push(`
<section class="cta" id="cta">
  <h2>${esc(copy.cta.heading)}</h2>
  <p>${esc(copy.cta.subheading)}</p>
  <a class="btn" href="#">${esc(copy.cta.button)}</a>
</section>`);
  }

  return parts.join("\n");
}

export function buildExportHtml(
  copy: CopyJson,
  page: PageJson,
  projectName: string,
  templateId: TemplateId,
): string {
  const colorMode = (page.color_mode ?? "light") as ColorMode;
  const palette = resolveColorPalette(page, templateId);
  const vars = paletteToCssVars(templateId, palette, colorMode);

  return `<!DOCTYPE html>
<html lang="en" data-theme="${colorMode}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${esc(projectName)} — Landing Page</title>
  <style>
    :root {
${cssBlock(vars)}
      --font: system-ui, sans-serif;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: var(--font);
      background: var(--bg, var(--background, #fff));
      color: var(--text, var(--fg, #111));
      line-height: 1.6;
      padding: 0 24px 48px;
    }
    .wrap { max-width: 720px; margin: 0 auto; }
    header { padding: 24px 0; border-bottom: 1px solid var(--rule, #ddd); margin-bottom: 48px; }
    header strong { font-size: 1.25rem; }
    .hero { padding: 48px 0; }
    .hero h1 { font-size: clamp(2rem, 5vw, 3.5rem); line-height: 1.05; margin-bottom: 1rem; }
    .sub { opacity: 0.75; font-size: 1.125rem; margin-bottom: 2rem; max-width: 540px; }
    .btn {
      display: inline-block;
      background: var(--accent);
      color: var(--accent-on, var(--accent-ink, #fff));
      padding: 14px 28px;
      border-radius: 999px;
      text-decoration: none;
      font-weight: 600;
    }
    .block { padding: 48px 0; border-top: 1px solid var(--rule, #eee); }
    .block h2 { font-size: 1.75rem; margin-bottom: 1rem; }
    .features { list-style: none; display: grid; gap: 1.5rem; }
    .features li strong { display: block; margin-bottom: 0.25rem; }
    .cta { padding: 64px 0; text-align: center; }
    .cta h2 { font-size: 2.5rem; margin-bottom: 1rem; }
    footer { margin-top: 48px; padding-top: 24px; border-top: 1px solid var(--rule, #eee); font-size: 0.875rem; opacity: 0.6; }
  </style>
</head>
<body>
  <div class="wrap">
    <header><strong>${esc(projectName)}</strong></header>
    <main>
${sectionHtml(copy)}
    </main>
    <footer>Generated by Fivvle · Template: ${esc(templateId)} · Palette: ${esc(palette.preset)}</footer>
  </div>
</body>
</html>`;
}

export function downloadExportHtml(
  copy: CopyJson,
  page: PageJson,
  projectName: string,
  templateId: TemplateId,
): void {
  const html = buildExportHtml(copy, page, projectName, templateId);
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${projectName.replace(/\s+/g, "-").toLowerCase()}-landing.html`;
  a.click();
  URL.revokeObjectURL(url);
}
